# Generated by Django 2.1 on 2018-08-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('idBarb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Barber')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
