# Generated by Django 2.1 on 2018-08-08 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20180808_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('discount', models.PositiveIntegerField(verbose_name='disconto')),
            ],
        ),
        migrations.CreateModel(
            name='OfferService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Offer')),
            ],
        ),
        migrations.DeleteModel(
            name='Promocao',
        ),
        migrations.DeleteModel(
            name='SOffer',
        ),
        migrations.AlterField(
            model_name='barber',
            name='name',
            field=models.CharField(max_length=30, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=64, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=30, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='num_Tel',
            field=models.CharField(max_length=9, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='historys',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='preço'),
        ),
        migrations.AddField(
            model_name='offerservice',
            name='idService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Service'),
        ),
    ]
