# Generated by Django 2.1 on 2018-08-10 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20180809_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Offer')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Service')),
            ],
        ),
    ]
