# Generated by Django 2.1 on 2018-08-10 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_offerservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barber',
            options={'verbose_name': 'barbeiro'},
        ),
        migrations.AlterModelOptions(
            name='historys',
            options={'verbose_name': 'Registro'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Promoçõe'},
        ),
        migrations.AlterModelOptions(
            name='offerservice',
            options={'verbose_name': 'Promoções/Produto'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Serviço'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.PositiveIntegerField(verbose_name='desconto'),
        ),
        migrations.AlterField(
            model_name='offerservice',
            name='idOffer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Offer', verbose_name='Promoção'),
        ),
        migrations.AlterField(
            model_name='offerservice',
            name='idService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Service', verbose_name='serviço'),
        ),
    ]
